### ISSUE TITLE
Still not working on Ubuntu

### ISSUE THREAD

**Issue by voxkmp** [pharo-spec/gtk-bindings#1]
I see that the Pharo-Mars code has been split into two projects. Unfortunately this has still not fixed the problem with Ubuntu. It is still totally impossible to run pharo mars on ubuntu.

Just loading the GTK-bindings package into ubuntu causes a segfault.
Xubuntu 20.04 64-bit - I followed the instructions on gtk-bindings readme page.

Crash report attached
[crash.txt](https://github.com/pharo-spec/gtk-bindings/files/5422658/crash.txt)

**Comment by voxkmp** [comment]
Now loads but crashes on illegal instruction when attempting to open a window. Crash dump attached
[crash .txt](https://github.com/pharo-spec/gtk-bindings/files/5501048/crash.txt)

**Comment by nodrygo** [comment]
I have the same problem on my Linux Mint 19.3 Cinnamon

**Comment by voxkmp** [comment]
The bug does not appear to be because I'm using an old version of Gtk.

if I type dpkg -l libgtk2.0-0 libgtk-3-0

I get :

+++-=================-================-============-===========================>
ii  libgtk-3-0:amd64  3.24.20-0ubuntu1 amd64        GTK graphical user interfac>
ii  libgtk2.0-0:amd64 2.24.32-4ubuntu4 amd64        GTK graphical user interfac>
lines 1-7/7 (END)

So the version is 3.24.20 - this shoudl be OK

**Comment by voxkmp** [comment]
Tried again after seeing that a test for minimum version of GTK had been added.

Now I get a crash just on trying to load the bindings, Crash report attached
[crash .txt](https://github.com/pharo-spec/gtk-bindings/files/5709820/crash.txt)

**Comment by voxkmp** [comment]
Works now with latest Pharo 9 and headless VM

/home/kmp/Documents/Technical/Pharo/mars6000/Pharo.image
Pharo9.0.0
Build information: Pharo-9.0.0+build.1379.sha.41c784432d862fe44618f04ac8a6ab502e737df3 (64 Bit)
Unnamed

irtual Machine
/home/kmp/Documents/Technical/Pharo/mars6000/pharo-vm/lib/pharo
CoInterpreter VMMaker-tonel.1 uuid: 286e9806-8e7d-0d00-ab06-4e280faf8631 Apr 30 2021
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 286e9806-8e7d-0d00-ab06-4e280faf8631 Apr 30 2021
5125110 - Commit: 5125110 - Date: 2021-04-30 10:05:04 +0200

Pharo 9.0.0 built on Apr 30 2021 10:22:47 Compiler: 5.4.0 20160609
VMMaker versionString 5125110 - Commit: 5125110 - Date: 2021-04-30 10:05:04 +0200
CoInterpreter VMMaker-tonel.1 uuid: 286e9806-8e7d-0d00-ab06-4e280faf8631 Apr 30 2021
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 286e9806-8e7d-0d00-ab06-4e280faf8631 Apr 30 2021
